package com.example.exploedview

data class Data (
    val features: ArrayList<String>?,
    val geometry: String?,
    val coordinates: ArrayList<String>?,
    val properties: ArrayList<String>?,
    val apt_no: String?,
    val adm_cd: String?,
    val bd_mgt_sn: String?,
    val buld_nm: String?,
    val buld_nm_dc: String?,
    val ho_nm: String?,
    val hhd_sum: String?,
    val seq_no: String?,
    val apt_type: String?,
    val nso_nm: String?,
    val nso_nm_dc: String?,
    val hu_num_yn: String?,
    val poed_group: String?,
    val coord_x: String?,
    val coord_y: String?,
    val poed_cd: String?,
    val poed_nm: String?,
    val hu_num: String?,
    val poed_txt: String?,
    val poed_nmtxt: String?,
    val budi_id: String?,
    val poed_grp2: String?,
    val c_poed_cd: String?,
    val c_poed_txt: String?,
    val prt_nm: String?,
    val prt_nm_dc: String?,
    val make_date: String?,
    val stair_date: String?,
    val poed_date: String?,
    val stair_grp: String?,
    val no_stair_grp: String?,
    val no_stair_g: String?,
    val surv_id: String?,
    val delete_yn: String?,
    val id: String?,
)